name: Deploy to Firebase Hosting on merge
on:
#   push:
#     branches:
#       - 'main'

  workflow_dispatch:
    inputs:
      branch:
        description: Branch to build
        required: true
        default: main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies & build
        run: npm ci && npm run build
        env:
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
          REACT_APP_API_KEY: ${{ vars.REACT_APP_API_KEY }}
          REACT_APP_AUTH_DOMAIN: ${{ vars.REACT_APP_AUTH_DOMAIN }}
          REACT_APP_PROJECT_ID: ${{ vars.REACT_APP_PROJECT_ID }}
          REACT_APP_STORAGE_BUCKET: ${{ vars.REACT_APP_STORAGE_BUCKET }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ vars.REACT_APP_MESSAGING_SENDER_ID }}
          REACT_APP_APP_ID: ${{ vars.REACT_APP_APP_ID }}
          REACT_APP_MEASUREMENT_ID: ${{ vars.REACT_APP_MEASUREMENT_ID }}

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FINTRACK_119 }}
          channelId: live
          projectId: fintrack-119
